config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registration: 'users/registration',
    passwords: 'users/passwords'
  }

  get 'rating/index'

  get 'progress/show'
  post 'progress/:test_id/details', to: 'progress#details', as: :progress_details
  post 'progress/:test_id/hide', to: 'progress#hide', as: :progress_hide

  resources :tests do
    get 'start', to: 'tests#start', as: :start
    get 'result', to: 'tests#result', as: :result
  end

  get 'questions/:question_id', to: 'questions#show', as: :question_show
  post 'questions/:question_id/answer', to: 'questions#answer', as: :question_answer

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  def to_s
    text
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
end

app/models/completed_test.rb
class CompletedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :right_answer, class_name: 'Answer', optional: true
  has_many :answers

  def to_s
    text
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions
  has_many :completed_tests

  def number_tries(user)
    completed_tests.where(user: user).size
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/progress_controller.rb
class ProgressController < ApplicationController
  before_action :authenticate_user!

  def show
    @completed_tests = ProgressService.completed_tests(current_user)
    @completed_tests_count = @completed_tests.count
    @test_count = Test.count
  end

  def details
    @test = Test.find(params[:test_id])
    @completed_tests_records = ProgressService.completed_tests_records(current_user, @test)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def hide
    @completed_test = Test.find(params[:test_id])

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:question_id])
    @count_questions = TestsService.count_questions
    @current_question_index = TestsService.current_question_index
  end

  def answer
    TestsService.answer(params[:answer].to_i)

    if TestsService.test_completed?
      TestsService.complete_test(current_user)
      redirect_to test_result_path(TestsService.test)
    else
      redirect_to question_show_path(TestsService.next_question)
    end
  end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order(rating: :desc)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def start
    test = Test.find(params[:test_id])
    TestsService.start_test(test)
    redirect_to question_show_path(test.questions.first)
  end

  def result
    @right_answers_count = TestsService.right_answers_count
    @count_questions = TestsService.count_questions
    @results = TestsService.results
    @questions = TestsService.questions
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/home/index.html.erb
<div class="text-center mt-4">
  <h1>Добро пожаловать!</h1>
  <h3 class="mt-4">Здесь вы можете проходить тесты по языку программирования Ruby</h3>
  <h3 class="mt-4">Чтобы начать проходить тесты, войдите или зарегистрируйтесь в системе</h3>
  <div class="d-grid gap-2 col-4 mx-auto pt-5">
    <%= link_to 'Войти', new_user_session_path, class: "btn btn-danger text-black btn-lg mt-4 h3" %>
    <%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-danger text-black btn-lg mt-4 h3" %>
    <%= link_to 'Войти как администратор', new_admin_session_path, class: "btn btn-danger text-black btn-lg mt-4 h3" %>
  </div>
</div>

app/views/progress/_completed_test.html.erb
<div id="<%= dom_id completed_test %>" class="col">
  <div class="card mt-4">
    <div class="card-body">
      <h4 class="card-title text-center"><%= completed_test.title %></h4>
      <p class="card-text">Категория: <%= completed_test.category.title.downcase %></p>
      <%= button_to "Подробнее", progress_details_path(completed_test), remote: true, class: "btn btn-danger text-black" %>
    </div>
  </div>
</div>

app/views/progress/details.turbo_stream.erb
<%= turbo_stream.replace dom_id(@test) do %>
  <div class="col" id="<%= dom_id(@test) %>">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center mb-4"><%= @test.title %></h4>
        <% @completed_tests_records.each do |record| %>
          <div class="card-text">
            <p>Дата прохождения: <%= record.created_at.strftime('%d/%m/%Y') %></p>
            <p>Количество правильных ответов: <%= record.right_answers_count %> </p>
            <p>Количество вопросов: <%= record.questions_count %></p>
          </div>
          <hr>
        <% end %>
        <%= button_to "Свернуть", progress_hide_path(@test), remote: true, class: "btn btn-danger text-black mt-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/progress/hide.turbo_stream.erb
<%= turbo_stream.replace dom_id(@completed_test) do %>
  <%= render partial: "completed_test", locals: { completed_test: @completed_test } %>
<% end %>

app/views/progress/show.html.erb
<div class="text-center mt-4">
  <h3>Пройденные тесты (пройдено <%= @completed_tests_count %> из <%= @test_count %>)</h3>
</div>

<div class="row row-cols-4">
  <% @completed_tests.each do |completed_test| %>
    <%= render partial: "completed_test", locals: { completed_test: completed_test } %>
  <% end %>
</div>

app/views/rating/index.html.erb
<h1 class="text-center mt-4">Рейтинг пользователей</h1>

<!--<div>-->
<!--  <p>Ваш рейтинг - <%#= current_user.rating %></p>-->
<!--</div>-->

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Место</th>
      <th scope="col">Email</th>
      <th scope="col">Рейтинг</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= user.email %></td>
      <td><%= user.rating %></td>
    </tr>
  <% end %>
  </tbody>
</table>