config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registration: 'users/registration',
    passwords: 'users/passwords'
  }

  get 'rating/index'

  get 'progress/show'
  post 'progress/:test_id/details', to: 'progress#details', as: :progress_details
  post 'progress/:test_id/hide', to: 'progress#hide', as: :progress_hide

  resources :tests do
    get 'start', to: 'tests#start', as: :start
    get 'result', to: 'tests#result', as: :result
  end

  get 'questions/:question_id', to: 'questions#show', as: :question_show
  post 'questions/:question_id/answer', to: 'questions#answer', as: :question_answer

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  def to_s
    text
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
end

app/models/completed_test.rb
class CompletedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :right_answer, class_name: 'Answer', optional: true
  has_many :answers

  def to_s
    text
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions
  has_many :completed_tests

  def number_tries(user)
    completed_tests.where(user: user).size
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/progress_controller.rb
class ProgressController < ApplicationController
  before_action :authenticate_user!

  def show
    @completed_tests = ProgressService.completed_tests(current_user)
    @completed_tests_count = @completed_tests.count
    @test_count = Test.count
  end

  def details
    @test = Test.find(params[:test_id])
    @completed_tests_records = ProgressService.completed_tests_records(current_user, @test)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def hide
    @completed_test = Test.find(params[:test_id])

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:question_id])
    @count_questions = TestsService.count_questions
    @current_question_index = TestsService.current_question_index
  end

  def answer
    TestsService.answer(params[:answer].to_i)

    if TestsService.test_completed?
      TestsService.complete_test(current_user)
      redirect_to test_result_path(TestsService.test)
    else
      redirect_to question_show_path(TestsService.next_question)
    end
  end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order(rating: :desc)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def start
    test = Test.find(params[:test_id])
    TestsService.start_test(test)
    redirect_to question_show_path(test.questions.first)
  end

  def result
    @right_answers_count = TestsService.right_answers_count
    @count_questions = TestsService.count_questions
    @results = TestsService.results
    @questions = TestsService.questions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <div data-controller="flash" class="alert alert-danger text-center position-fixed" role="alert"><%= msg %></div>
  <% else %>
    <div data-controller="flash" class="alert alert-primary text-center position-fixed" role="alert"><%= msg %></div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav bg-danger position-relative">
  <li class="nav-item">
    <%= link_to "Главная", root_path, class: "nav-link h3 text-black" %>
  </li>
  <li class="nav-item">
    <%= link_to "Тесты", tests_path, class: "nav-link h3 text-black" %>
  </li>
  <li class="nav-item">
    <%= link_to "Прогресс", progress_show_path, class: "nav-link h3 text-black" %>
  </li>
  <li class="nav-item">
    <%= link_to "Рейтинг", rating_index_path, class: "nav-link h3 text-black" %>
  </li>

  <% if user_signed_in? %>
    <li class="nav-item position-absolute top-0 end-0">
      <%= link_to "Профиль - " + current_user.email, edit_user_registration_path, class: "nav-link h3 text-black" %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
<!--    <p class="notice"><%#= notice %></p>-->
    <%= yield %>
  </body>
</html>